# Generated by Django 4.0.1 on 2022-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=250),
        ),
    ]
