# Generated by Django 4.0.1 on 2022-10-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='image',
        ),
    ]
